[book]
title = "Gen-UI Book"
authors = ["Will SHENG <syf20020816@outlook.com>"]
language = "en"
multilingual = false
src = "src"

[rust]
edition = "2021"

[build]
# extra-watch-dirs = ["po", "third_party"]

[preprocessor.gettext]
after = ["links"]

[output.html]
git-repository-url = "https://github.com/palpus-rs/Gen-UI.github.io"
